export { ApiClient } from "@/lib/sdk/client";
export { sdk } from "@/lib/sdk/facade";
export type { Sdk } from "@/lib/sdk/facade";
export { contentSdk } from "@/lib/sdk/domains/content";
export { dashboardSdk } from "@/lib/sdk/domains/dashboard";
export { uploadsSdk } from "@/lib/sdk/domains/uploads";
export { userSdk } from "@/lib/sdk/domains/user";
export { userPreferencesSdk } from "@/lib/sdk/domains/user-preferences";
export { publishSdk } from "@/lib/sdk/domains/publish";
export { notificationsSdk } from "@/lib/sdk/domains/notifications";
export { settingsSdk } from "@/lib/sdk/domains/settings";
export { metaSdk } from "@/lib/sdk/domains/meta";
